global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:

scrape_configs:
  - job_name: java
    scrape_interval: 1s
    static_configs:
      - targets:
          - host.docker.internal:8089