# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Build

on:
  push:
    branches: [ master, spring-issues ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Install component locally
      run: ./gradlew publishToMavenLocal
    - name: Check for Spring 2.3 conflicts
      run: cd spring-2.3-compatibility; mvn -Dqontract.version=`cat ../version.properties | cut -d = -f 2` test
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Qontract Standalone Executable
        path: application/build/libs/qontract.jar
